cephadm: fix unit tests.
Fixes AttributeError: 'FakePipeWrapper' object has no attribute 'readable'

Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
(cherry picked from commit 61cfaec7002caadb3b4e09d672919ed159853311)