cephadm: add log warn when unable to infer mon ip addr
fixup for `--mon-ip` bootstrap test (introduced b3e2c43):
  ValueError: 'eth0' does not appear to be an IPv4 or IPv6 address

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit ae7271d47da01dfeb90ed643da2cba91fc8fa2ce)