mgr/{prometheus,restful}: Fix url generation again
Fixes

```
======================================================================
ERROR: test_standby (tasks.mgr.test_prometheus.TestPrometheus)
----------------------------------------------------------------------
urllib3.exceptions.LocationParseError: Failed to parse: http://172.21.15.71:7789metrics

```

Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
(cherry picked from commit 45361ea9b3dab917a455bc37bc96aabd0bf64fcf)